### ISSUE TITLE
Unable to build for Android

### ISSUE THREAD

**Issue by bbjay** [bhagat-techind/app_state_checker#4]
I'm using app_state_checker: ^1.0.2+1
Builds fine for iOS, but fails for android:

```
Launching lib/main.dart on sdk gphone64 arm64 in debug mode...

FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':app_state_checker'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file: /Users/user/.pub-cache/hosted/pub.dev/app_state_checker-1.0.2+1/android/build.gradle. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.

     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --stacktrace option to get the stack trace.
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.
> Get more help at https://help.gradle.org.

BUILD FAILED in 9s
Error: Gradle task assembleStagingDebug failed with exit code 1

Exited (1)
```

<details>
<summary>flutter doctor output</summary>

```
[✓] Flutter (Channel stable, 3.35.4, on macOS 15.6 24G84 darwin-arm64, locale de-CH)
[✓] Android toolchain - develop for Android devices (Android SDK version 36.0.0)
[✓] Xcode - develop for iOS and macOS (Xcode 16.4)
[✓] Chrome - develop for the web
[✓] Android Studio (version 2025.1)
[✓] VS Code (version 1.104.2)
[✓] Connected device (6 available)
[✓] Network resources

• No issues found!

```
</details>

**Comment by bhagat-techind** [comment]
Hi @bbjay,
Thank you for reaching out.
This issue has been fixed in the latest version. Please check and let me know if you face any further problems.

**Comment by bbjay** [comment]
Thanks for your reply. Unfortunately I still get an error with the latest version, but a different one:

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileProductionDebugJavaWithJavac'.
> Compilation failed; see the compiler output below.
  /Users/user/Documents/projects/myapp/android/app/src/main/java/io/flutter/plugins/GeneratedPluginRegistrant.java:29: error: cannot find symbol
        flutterEngine.getPlugins().add(new com.techind.app_state_checker.AppStateCheckerPlugin());
                                                                        ^
    symbol:   class AppStateCheckerPlugin
    location: package com.techind.app_state_checker
  1 error

* Try:
> Check your code and dependencies to fix the compilation error(s)
> Run with --scan to get full insights.
```
